
GOOGLE_WORD2VEC_PATH = 'word2vec//GoogleNews-vectors-negative300.bin'
METHOD = 'CONCATENATE'

# BoostSRL parameters
NODESIZE = 2
NUMOFCLAUSES = 8
MAXTREEDEPTH = 3
TREES = 10
SEED = 441773
REFINE = None