from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from ekphrasis.classes.segmenter import Segmenter
from collections import OrderedDict
from scipy import spatial
import numpy as np
import operator
import logging
import sys, os

import logging
logging.basicConfig(level=logging.INFO)

#segmenter using the word statistics from Wikipedia
seg = Segmenter(corpus="english")

class Transfer:

  def __init__(self):
    pass

  def build_triples(self, data):
    """
       Splits predicates and its literals

       Args:
            data(str): relation to be split
       Returns:
            relation as a three-element array

        Example: 
            movie(A) -> movie, A, ''
            father(A,B) -> father, A, B
    """
    output = []
    for d in data:
      d = d.split('(')
      d_predicate = d[0]

      if(',' in d[1]):
        d_literal_1 = d[1].split(',')[0]
        d_literal_2 = d[1].split(',')[1].split(')')[0]
      else:
        d_literal_1 = d[1].split(',')[0]
        d_literal_2 = ''

      output.append([d_predicate, d_literal_1, d_literal_2])

    return output

  def get_arrays_avg(self, data):
    """
        Calculate the average fo word embeddings element-wise

        Args:
            data(array): an array containing word embeddings
       Returns:
            a single array generated by taking the element-wise average
    """

    N = len(data)
    avg = np.array(data[0])
    for i in range(1, len(data)):
        avg += np.array(data[i])
    return np.divide(avg, N)

  def build_model_array(self, data, model, relation='AVG'):
	  """
        Turn relations into a single array

        Args:
            data(array): an array containing word embeddings
            model(object): embedding model
            relation(str): method to compact arrays of embedded words
       Returns:
            a dictionary that the keys are the words and the values are single arrays of embeddings
    """

    dict = {}
    for example in data:
      temp = []

      # Tokenize relation words
      predicate = seg.segment(example[1])
      for word in predicate.split():
        temp.append(model.wv[word.lower().strip()])

      if(relation == 'AVG'):
        predicate = self.get_arrays_avg(temp)
      elif(relation == 'MAX'):
        predicate = max(temp, key=operator.methodcaller('tolist'))
      elif(relation == 'MIN'):
        predicate = min(temp, key=operator.methodcaller('tolist'))
      elif(relation == 'CONCATENATE'):
        predicate = min(temp, key=operator.methodcaller('tolist'))
        maximum = max(temp, key=operator.methodcaller('tolist'))
        predicate = np.append(predicate, maximum)

      dict[example.rstrip()] = predicate
    return dict

  def get_cosine_similarities(self, source, target):
    """
        Calculate cosine similarity of embedded arrays
        for all possible pairs (source, target)

        Args:
            source(array): all word embeddings from the source dataset
            target(array): all word embeddings from the target dataset
       Returns:
            a pandas dataframe containing every pair (source, target) similarity
    """

    similarity = {}
    for s in source:
      for t in target:
        key = s + ',' + t
        similarity[key] = 1 - spatial.distance.cosine(source[s], target[t])

    df = pd.DataFrame.from_dict(similarity, orient="index", columns=['similarity'])
    return df

  def similarity_word2vec(self, source, target, model_path, method):
     """
        Embed relations using pre-trained word2vec

        Args:
            source(array): all predicates from source dataset
            target(array): all predicates from target dataset
            model_path(str): current path to find the model to be used
            method(str): method used to compact arrays
       Returns:
             a pandas dataframe containing every pair (source, target) similarity
    """

    # Load Google's pre-trained Word2Vec model.
    word2vecModel = KeyedVectors.load_word2vec_format(model_path, binary=True, unicode_errors='ignore')

    source = self.build_model_array(source, word2vecModel, method=method)
    target = self.build_model_array(target, word2vecModel, method=method)

    return self.get_cosine_similarities(source, target)