
from gensim.test.utils import datapath, get_tmpfile
from ekphrasis.classes.segmenter import Segmenter
from gensim.models import KeyedVectors, Word2Vec
from collections import OrderedDict
import parameters as params
from scipy import spatial
from tqdm import tqdm
import utils as utils
import pandas as pd
import numpy as np
import fasttext
import operator
import logging
import sys
import os
import re

import logging
logging.basicConfig(level=logging.INFO)

# segmenter using the word statistics from Wikipedia
seg = Segmenter(corpus="english")

class Transfer:

  def __init__(self):
    pass

  def get_arrays_avg(self, data):
    """
        Calculate the average fo word embeddings element-wise

        Args:
            data(array): an array containing word embeddings
       Returns:
            a single array generated by taking the element-wise average
    """

    N = len(data)
    avg = np.array(data[0])
    for i in range(1, N):
        avg += np.array(data[i])
    return np.divide(avg, N)

  def build_model_array(self, data, model, method='AVG'):
    """
        Turn relations into a single array

        Args:
            data(array): an array containing word embeddings
            model(object): embedding model
            method(str): method to compact arrays of embedded words
       Returns:
            a dictionary that the keys are the words and the values are single arrays of embeddings
    """

    #logging.info('Building embeddings')

    dict = {}
    for example in tqdm(data):
      temp = []

      # Tokenize words of relation
      predicate = seg.segment(example[0])
      for word in predicate.split():
        try:
          #temp.append(model.wv[word.lower().strip()])
          temp.append(model.get_word_vector(word.lower().strip()))
        except:
          logging.warning('Word {} not present in pre-trained model'.format(word.lower().strip()))
          temp.append([0] * params.EMBEDDING_DIMENSION)
    
      if(method == 'AVG'):
        predicate = self.get_arrays_avg(temp)
      elif(method == 'MAX'):
        predicate = max(temp, key=operator.methodcaller('tolist'))
      elif(method == 'MIN'):
        predicate = min(temp, key=operator.methodcaller('tolist'))
      elif(method == 'CONCATENATE'):
        #predicate = min(temp, key=operator.methodcaller('tolist'))
        #maximum = max(temp, key=operator.methodcaller('tolist'))
        predicate = np.concatenate(temp)

      if(example[2] == ''):
        example.remove('')
      dict[example[0].rstrip()] = [predicate, example[1:]]
    return dict

  def get_cosine_similarities(self, source, target):
    """
        Calculate cosine similarity of embedded arrays
        for all possible pairs (source, target)

        Args:
            source(array): all word embeddings from the source dataset
            target(array): all word embeddings from the target dataset
       Returns:
            a pandas dataframe containing every pair (source, target) similarity
    """

    logging.info('Calculating similarities')

    similarity = {}
    for s in tqdm(source):
      for t in tqdm(target):

      	# Predicates must have the same arity
        if(len(source[s][1]) != len(target[t][1])):
          continue

        key = s + '(' + ','.join(source[s][1]) + ')' + ',' + t + '(' + ','.join(target[t][1]) + ')'
        #key = s + '(' + ','.join([chr(65+i) for i in range(len(source[s][1]))]) + ')' + ',' + t + '(' + ','.join([chr(65+i) for i in range(len(target[t][1]))]) + ')'
        if(source[s][0].shape[0] != target[t][0].shape[0]):
          source[s][0], target[t][0] = utils.fill_dimension(source[s][0], target[t][0], params.EMBEDDING_DIMENSION)

        similarity[key] = 1 - spatial.distance.cosine(source[s][0], target[t][0])

    df = pd.DataFrame.from_dict(similarity, orient="index", columns=['similarity'])
    return df

  def similarity_word2vec(self, source, target, model_path, method):
    """
        Embed relations using pre-trained word2vec

        Args:
            source(array): all predicates from source dataset
            target(array): all predicates from target dataset
            model_path(str): current path to find the model to be used
            method(str): method used to compact arrays
       Returns:
             a pandas dataframe containing every pair (source, target) similarity
    """

    # Load Google's pre-trained Word2Vec model.
    logging.info('Loading pre-trained Word2Vec model')
    word2vecModel = KeyedVectors.load_word2vec_format(model_path, binary=True)

    source = utils.build_triples(source)
    target = utils.build_triples(target)

    source = self.build_model_array(source, word2vecModel, method=method)
    target = self.build_model_array(target, word2vecModel, method=method)

    return self.get_cosine_similarities(source, target)

  def similarity_fasttext(self, source, target, fastTextModel, method):
    """
        Embed relations using pre-trained fasttext

        Args:
            source(array): all predicates from source dataset
            target(array): all predicates from target dataset
            model_path(str): current path to find the model to be used
            method(str): method used to compact arrays
       Returns:
            a pandas dataframe containing every pair (source, target) similarity
    """

    # Load Wikipedia's pre-trained fastText model.
    #logging.info('Loading pre-trained fastText model.')
    #fastTextModel = fasttext.load_model(params.WIKIPEDIA_FASTTEXT_PATH)

    source = utils.build_triples(source)
    target = utils.build_triples(target)

    source = self.build_model_array(source, fastTextModel, method=method)
    target = self.build_model_array(target, fastTextModel, method=method)

    return self.get_cosine_similarities(source, target)

  def map_predicates(self, source, similarity, recursion=False, searchArgPermutation=False, searchEmpty=False, allowSameTargetMap=False):
      """
        Sorts dataframe to obtain the closest target to a given source

        Args:
            source(array): all predicates from source dataset
            similarity(dataframe): a pandas dataframe containing every pair (source, target) similarity
        Returns:
            a dictionary containing all predicates mapped
      """

      logging.info('Mapping source to target predicates given the highest similaries')

      target_mapped, mapping = [], {}
      indexes = similarity.sort_values(by='similarity', ascending=False).index.tolist()
      
      for index in tqdm(indexes):
        index = re.split(r',\s*(?![^()]*\))', index)
        source, target = index[0].rstrip(), index[1].rstrip()

        if(source in mapping):
          continue

        if(allowSameTargetMap):
          mapping[source] = target
        else:
          if(target in target_mapped):
            continue
          else:
            mapping[source] = target
            target_mapped.append(target)

        if(len(mapping) == len(source)):
          # All sources mapped to a target
          break

      return mapping

  def write_to_file_closest_distance(self, from_predicate, to_predicate, arity, mapping, filename, recursion=False, searchArgPermutation=False, searchEmpty=False, allowSameTargetMap=False):
    """
          Sorts dataframe to obtain the closest target to a given source

          Args:
              from_predicate(str): predicate of model trained using source data
              to_predicate(str): predicate of model to be trained transfering the structure of source model
              arity(int): arity of from and to predicate
              mapping(dict): a dictionary a pair of mapping (source, target)
         Returns:
              writes a file containing transfer information
    """
    with open(params.TRANSFER_FILENAME, 'w') as file:
      for source in mapping.keys():
        file.write((source + ': ' + mapping[source]).replace('`', ''))
        file.write('\n')

      file.write('setMap:' + from_predicate + '(' + ','.join([chr(65+i) for i in range(arity)]) + ')' + ',' + to_predicate + '(' + ','.join([chr(65+i) for i in range(arity)]) + ')' + '\n')
      if(recursion):
          file.write('setMap:recursion_' + from_predicate + '(A,B)=recursion_' + to_predicate + '(A,B).\n')
      #file.write('setParam:searchArgPermutation=' + str(searchArgPermutation).lower() + '.\n')
      #file.write('setParam:searchEmpty=' + str(searchEmpty).lower() + '.\n')
      file.write('setParam:allowSameTargetMap=' + str(allowSameTargetMap).lower() + '.\n')
    file.close()

    with open(filename + '/transfer.txt', 'w') as file:
      for source in mapping.keys():
        file.write((source + ': ' + mapping[source]).replace('`', ''))
        file.write('\n')

      file.write('setMap:' + from_predicate + '(' + ','.join([chr(65+i) for i in range(arity)]) + ')' + ',' + to_predicate + '(' + ','.join([chr(65+i) for i in range(arity)]) + ')' + '\n')
      if(recursion):
          file.write('setMap:recursion_' + from_predicate + '(A,B)=recursion_' + to_predicate + '(A,B).\n')
      #file.write('setParam:searchArgPermutation=' + str(searchArgPermutation).lower() + '.\n')
      #file.write('setParam:searchEmpty=' + str(searchEmpty).lower() + '.\n')
      file.write('setParam:allowSameTargetMap=' + str(allowSameTargetMap).lower() + '.\n')
    file.close()